title_primary: "天仙子" # the bigger text
title_secondary: "文字森林" # the smaller text
keywords:
language: zh-cn


twitter: #username
rss: atom.xml
weibo: #username/id
instagram: #username
github: #Mimismeow

# Choose the comment service according to your need.
# Please do not use the two services at the same time.
livere: # [data-uid] on livere.com
disqus: # [short_name] on disqus.com
dove: # For fun ONLY. Set to true to 'disable' comments on your site.

# Set true to show the page indicator.
showPageCount: true

# Set true to show category or tags behind post titles
showCategories: true
showTags: true

# Color scheme
themeStyle: light # light/dark